domain_path: C:\Users\Admin\Downloads\TRNG_vitis\Nhung\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\2025.1.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
